/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 *
 ******************************************************************************
 */

/**************************Includes******************************/

#include "APP_INIT.h"

#define clock	36000000

TaskHandle_t Openloop_test = NULL ;
void OpenloopTest(void * x);
int main (){
	RCC_INIT();
	HW_INIT();

	xTaskCreate(OpenloopTest, "Open loop system test", 128, NULL, 1,&Openloop_test);

	vTaskStartScheduler();
	while(1)
	{

	}


	return 0;
}


void OpenloopTest(void * x)
{
	//detection mode
	HAL_Servo_Set_Angle(90, clock);
	HAL_MOTOR_Motion(FORWARD);
	delay(3000, U_ms, clock);

	//start point
	HAL_MOTOR_Motion(STOP);
	delay(250, U_ms, clock);

	//First arc mode
	HAL_Servo_Set_Angle(130, clock);
	HAL_MOTOR_Motion(REVERSE);
	delay(2898, U_ms, clock);
	HAL_MOTOR_Motion(STOP);
	delay(250, U_ms, clock);

	//straight line mode
	HAL_Servo_Set_Angle(90, clock);
	HAL_MOTOR_Motion(REVERSE);
	delay(3301, U_ms, clock);
	HAL_MOTOR_Motion(STOP);
	delay(250, U_ms, clock);

	//second arc mode
	HAL_Servo_Set_Angle(50, clock);
	HAL_MOTOR_Motion(REVERSE);
	delay(2898, U_ms, clock);
	HAL_MOTOR_Motion(STOP);
	delay(250, U_ms, clock);
	HAL_Servo_Set_Angle(90, clock);
}

